### PR TITLE
Added Collisions

### PR DESCRIPTION
**Pull request by afsyaw**
Added collisions to the meshes

### CODE REVIEW

**Comment by SteveMacenski** [comment]
Have you verified these in gazebo for any pose that the robot doesn't contact the ground plane making it spin off / "jump"? That was a problem when I removed them.

**Comment by afsyaw** [comment]
I tested them with the planner for a variety of poses and there were no
such issues.

As to its behavior if, for example, the end effector collided with the
ground...I am uncertain.

**Comment by SteveMacenski** [comment]
Your comment on the other thread reminded me of this PR. Did you test the robot in configurations below the (X,Y,0) plane? If it works, I will merge.

**Comment by afsyaw** [comment]
I did not attempt collisions with the ground plane; however, when mounted on a mobile base, goals with negative z values are accessible. 

In the image below, the end effector is at z = -0.1

gammap3dx

**Pull request merged**
